name = "ou-sion"
main = "src/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./"

[env.production]
name = "oouu-org-homepage"

[env.staging]
name = "oouu-org-homepage-staging"

